version: "2"

linters:
  enable:
    - thelper
    - tparallel
    - wastedassign
    - unparam
    - prealloc
    - unconvert
    - exhaustive
    - makezero
    - nakedret
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    nakedret:
      max-func-lines: 0

run:
  go: '1.21'
  timeout: 10m
